# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Aamir/Desktop/project_versions/basePro_bramS2/basePro_bramS2.srcs/sources_1/ip/instr_screen/instr_screen.xci
# IP: The module: 'instr_screen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aamir/Desktop/project_versions/basePro_bramS2/basePro_bramS2.srcs/sources_1/ip/instr_screen/instr_screen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_screen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Aamir/Desktop/project_versions/basePro_bramS2/basePro_bramS2.srcs/sources_1/ip/instr_screen/instr_screen.xci
# IP: The module: 'instr_screen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aamir/Desktop/project_versions/basePro_bramS2/basePro_bramS2.srcs/sources_1/ip/instr_screen/instr_screen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_screen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
