set_property PACKAGE_PIN W5 [get_ports clk_100M]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk_100M]
	
set_property PACKAGE_PIN V17 [get_ports game_on]					
	set_property IOSTANDARD LVCMOS33 [get_ports game_on]
set_property PACKAGE_PIN V16 [get_ports clear]					
	set_property IOSTANDARD LVCMOS33 [get_ports clear]
set_property PACKAGE_PIN W16 [get_ports pause]					
	set_property IOSTANDARD LVCMOS33 [get_ports pause]
	
	
set_property PACKAGE_PIN U1 [get_ports {clr}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {clr}]
set_property PACKAGE_PIN T1 [get_ports {sel}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sel}]
	
set_property PACKAGE_PIN R2 [get_ports {toggle_mouse_button}]					
        set_property IOSTANDARD LVCMOS33 [get_ports {toggle_mouse_button}]

##property PACKAGE_PIN U16 [get_ports {game_win}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {game_win}]
##_property PACKAGE_PIN E19 [get_ports in_shaded]					
	#set_property IOSTANDARD LVCMOS33 [get_ports in_shaded]
		
set_property PACKAGE_PIN U18 [get_ports game_start]						
	set_property IOSTANDARD LVCMOS33 [get_ports game_start]
set_property PACKAGE_PIN T18 [get_ports up]						
	set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN W19 [get_ports left]						
	set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property PACKAGE_PIN T17 [get_ports right]						
	set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property PACKAGE_PIN U17 [get_ports down]						
	set_property IOSTANDARD LVCMOS33 [get_ports down]
		
set_property PACKAGE_PIN G19 [get_ports {vga_red[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_red[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_red[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_red[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[3]}]
set_property PACKAGE_PIN N18 [get_ports {vga_blue[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_blue[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_blue[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_blue[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[3]}]
set_property PACKAGE_PIN J17 [get_ports {vga_green[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_green[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_green[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_green[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[3]}]
set_property PACKAGE_PIN P19 [get_ports h_sync]						
	set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property PACKAGE_PIN R19 [get_ports v_sync]						
	set_property IOSTANDARD LVCMOS33 [get_ports v_sync]

# leds
set_property PACKAGE_PIN U16 [get_ports {led[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {game_win}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {game_win}]


##USB-RS232 Interface
#set_property PACKAGE_PIN B18 [get_ports RsRx]						
#	set_property IOSTANDARD LVCMOS33 [get_ports RsRx]
#set_property PACKAGE_PIN A18 [get_ports RsTx]						
	#set_property IOSTANDARD LVCMOS33 [get_ports RsTx]


#USB HID (PS/2)
set_property PACKAGE_PIN C17 [get_ports PS2Clk]						
	set_property IOSTANDARD LVCMOS33 [get_ports PS2Clk]
	set_property PULLUP true [get_ports PS2Clk]
set_property PACKAGE_PIN B17 [get_ports RsRx]					
	set_property IOSTANDARD LVCMOS33 [get_ports RsRx]	
	set_property PULLUP true [get_ports RsRx]
